"""Putting the instructions into a file an agent already reads.

``AGENTS.md`` and ``CLAUDE.md`` are where coding agents look for standing
instructions, so that is where a voice belongs. Writing it once is easy --
``llmtone prompt >> AGENTS.md`` does that. Writing it a second time is the
problem: the append leaves yesterday's profile above today's, and a file
holding two of them describes neither.

So the text goes between markers, and a later run replaces what is between
them and touches nothing else. Everything outside the markers is yours.
"""

from __future__ import annotations

from pathlib import Path

#: Marker lines. HTML comments, because every target file is markdown and a
#: comment is the one thing no renderer shows and no model mistakes for prose.
START = "<!-- llmtone:start -->"
END = "<!-- llmtone:end -->"

#: The default target. AGENTS.md is read natively by Codex, Cursor, Gemini CLI,
#: Copilot, Aider, Zed and others, which makes it the one file worth defaulting
#: to; CLAUDE.md is a `--write CLAUDE.md` away.
DEFAULT_TARGET = "AGENTS.md"

_SCOPE = (
    "When writing prose on this person's behalf -- documentation, comments,\n"
    "commit messages, replies -- match the voice below."
)


class BlockError(Exception):
    """The target file is not in a state we are willing to guess about."""


def refresh_command(target: str, context: str | None = None) -> str:
    """The command that regenerates this block, quoted back to the reader."""
    parts = ["llmtone prompt"]
    if context:
        parts.append(f"--context {context}")
    parts.append(f"--write {target}")
    return " ".join(parts)


def render_block(
    instructions: str,
    *,
    context: str | None = None,
    target: str = DEFAULT_TARGET,
) -> str:
    """Wrap rendered instructions in the managed block, markers included."""
    heading = "## Writing voice" + (f" ({context})" if context else "")
    return "\n".join(
        [
            START,
            "<!-- Generated by llmtone. Anything between these markers is",
            f"     replaced on the next run. Refresh: {refresh_command(target, context)} -->",
            "",
            heading,
            "",
            _SCOPE,
            "",
            instructions.strip(),
            END,
        ]
    )


def _marker_lines(lines: list[str], marker: str) -> list[int]:
    """Indexes of lines that are exactly ``marker``, at column zero.

    Column zero is deliberate. A marker indented into a fenced code block is
    documentation about llmtone, not an instruction to llmtone.
    """
    return [i for i, line in enumerate(lines) if line.rstrip() == marker]


def splice(existing: str | None, block: str) -> tuple[str, str]:
    """Put ``block`` into ``existing``, replacing any block already there.

    Returns the new text and one of ``created``, ``appended`` or ``replaced``.
    Raises :class:`BlockError` rather than guessing when the markers in the
    file do not make sense.
    """
    if existing is None or not existing.strip():
        return block + "\n", "created"

    newline = "\r\n" if "\r\n" in existing else "\n"
    lines = existing.replace("\r\n", "\n").split("\n")
    starts = _marker_lines(lines, START)
    ends = _marker_lines(lines, END)

    if len(starts) > 1 or len(ends) > 1:
        raise BlockError(
            "found more than one llmtone block. Leave a single "
            f"{START} / {END} pair and run this again."
        )
    if starts and not ends:
        raise BlockError(
            f"found {START} with no {END} after it. "
            "Close the block or delete the marker, then run this again."
        )
    if ends and not starts:
        raise BlockError(
            f"found {END} with no {START} before it. "
            "Open the block or delete the marker, then run this again."
        )
    if starts and ends and ends[0] < starts[0]:
        raise BlockError(
            f"found {END} before {START}. "
            "Put them the right way round, then run this again."
        )

    if starts:
        body = lines[: starts[0]] + block.split("\n") + lines[ends[0] + 1 :]
        action = "replaced"
    else:
        body = existing.replace("\r\n", "\n").rstrip("\n").split("\n")
        body += ["", *block.split("\n"), ""]
        action = "appended"

    text = "\n".join(body)
    if not text.endswith("\n"):
        text += "\n"
    return (text.replace("\n", "\r\n") if newline == "\r\n" else text), action


def write_block(path: Path, block: str) -> str:
    """Splice ``block`` into ``path``, creating the file if it is not there.

    UTF-8 both ways and no newline translation: the instructions name em dashes
    and en dashes, and a Windows default of cp1252 would fail on the first one.
    Returns what happened, for the caller to report.
    """
    try:
        with path.open("r", encoding="utf-8", newline="") as handle:
            existing = handle.read()
    except FileNotFoundError:
        existing = None
    except UnicodeDecodeError as exc:
        raise BlockError(f"{path} is not UTF-8 text, so it was left alone.") from exc
    except OSError as exc:
        raise BlockError(f"could not read {path}: {exc.strerror or exc}.") from exc

    new_text, action = splice(existing, block)

    try:
        with path.open("w", encoding="utf-8", newline="") as handle:
            handle.write(new_text)
    except OSError as exc:
        raise BlockError(f"could not write {path}: {exc.strerror or exc}.") from exc
    return action
